datasets:
  target: locals.datasets.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 4
    wrap: True
    train:
      - llava_pretrain_i2t:
        target: locals.datasets.image_caption.cc3m.FilteredCC3MI2TDataset
        params:
          path: /inspire/hdd/ws-f4d69b29-e0a5-44e6-bd92-acf4de9990f0/public-project/zhangwanlin-240108540162/VoCoT/offline/LLaVA-Pretrain/blip_laion_cc_sbu_558k.json
          image_folder: /inspire/hdd/ws-f4d69b29-e0a5-44e6-bd92-acf4de9990f0/public-project/zhangwanlin-240108540162/VoCoT/offline/LLaVA-Pretrain/images
          raw_image: True
          output_mode: text
          shuffle: False