- refcoco:
  target: locals.datasets.multimodal_tasks.refcoco.RefCOCOEvalDataset
  params:
    path: /mnt/bn/yangmin-priv/luoruipu/data/multimodal-datasets/Refcoco
    dataset_name: refcocog
    split: val
    split_by: umd
    image_path: PATH/TO/COCO2015/images/
    task_mode: t2i